# Generated by Django 4.2.5 on 2023-09-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(default='1980-01-01'),
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(default='exemplo@exemplo.com.br', max_length=254),
        ),
        migrations.AddField(
            model_name='autor',
            name='idade',
            field=models.PositiveSmallIntegerField(default='1'),
        ),
    ]
