# Generated by Django 4.2.5 on 2023-09-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_autor_data_nascimento_autor_email_autor_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.DateField(default='1980')),
                ('diretor', models.CharField(max_length=100)),
                ('sinopse', models.TextField(max_length=500)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='filmes/')),
            ],
        ),
    ]
